
[[override]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.6.4"

[[constraint]]
  name = "github.com/izumin5210/grapi"
  version = "0.3.2"
