
[[override]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.6.4"

[[constraint]]
  name = "github.com/izumin5210/grapi"
  version = "0.3.2"

[[constraint]]
  name = "github.com/golangci/golangci-lint"
  version = "1.12.5"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"
