// Code generated by github.com/izumin5210/grapi. DO NOT EDIT.

package github

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	github_pb "github.com/izumin5210/ghrsync/api/github"
)

// RegisterWithServer implements grapiserver.Server.RegisterWithServer.
func (s *installationEventServiceServerImpl) RegisterWithServer(grpcSvr *grpc.Server) {
	github_pb.RegisterInstallationEventServiceServer(grpcSvr, s)
}

// RegisterWithHandler implements grapiserver.Server.RegisterWithHandler.
func (s *installationEventServiceServerImpl) RegisterWithHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return github_pb.RegisterInstallationEventServiceHandler(ctx, mux, conn)
}
