// Code generated by protoc-gen-go. DO NOT EDIT.
// source: installation_event.proto

package github_pb // import "github.com/izumin5210/ghrsync/api/github"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Installation struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Installation) Reset()         { *m = Installation{} }
func (m *Installation) String() string { return proto.CompactTextString(m) }
func (*Installation) ProtoMessage()    {}
func (*Installation) Descriptor() ([]byte, []int) {
	return fileDescriptor_installation_event_3d701448f387c4fc, []int{0}
}
func (m *Installation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Installation.Unmarshal(m, b)
}
func (m *Installation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Installation.Marshal(b, m, deterministic)
}
func (dst *Installation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Installation.Merge(dst, src)
}
func (m *Installation) XXX_Size() int {
	return xxx_messageInfo_Installation.Size(m)
}
func (m *Installation) XXX_DiscardUnknown() {
	xxx_messageInfo_Installation.DiscardUnknown(m)
}

var xxx_messageInfo_Installation proto.InternalMessageInfo

func (m *Installation) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type InstallationEvent struct {
	Action               string                          `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Installation         *Installation                   `protobuf:"bytes,2,opt,name=installation,proto3" json:"installation,omitempty"`
	Repositories         []*InstallationEvent_Repository `protobuf:"bytes,3,rep,name=repositories,proto3" json:"repositories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *InstallationEvent) Reset()         { *m = InstallationEvent{} }
func (m *InstallationEvent) String() string { return proto.CompactTextString(m) }
func (*InstallationEvent) ProtoMessage()    {}
func (*InstallationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_installation_event_3d701448f387c4fc, []int{1}
}
func (m *InstallationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallationEvent.Unmarshal(m, b)
}
func (m *InstallationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallationEvent.Marshal(b, m, deterministic)
}
func (dst *InstallationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallationEvent.Merge(dst, src)
}
func (m *InstallationEvent) XXX_Size() int {
	return xxx_messageInfo_InstallationEvent.Size(m)
}
func (m *InstallationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_InstallationEvent proto.InternalMessageInfo

func (m *InstallationEvent) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *InstallationEvent) GetInstallation() *Installation {
	if m != nil {
		return m.Installation
	}
	return nil
}

func (m *InstallationEvent) GetRepositories() []*InstallationEvent_Repository {
	if m != nil {
		return m.Repositories
	}
	return nil
}

type InstallationEvent_Repository struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallationEvent_Repository) Reset()         { *m = InstallationEvent_Repository{} }
func (m *InstallationEvent_Repository) String() string { return proto.CompactTextString(m) }
func (*InstallationEvent_Repository) ProtoMessage()    {}
func (*InstallationEvent_Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_installation_event_3d701448f387c4fc, []int{1, 0}
}
func (m *InstallationEvent_Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallationEvent_Repository.Unmarshal(m, b)
}
func (m *InstallationEvent_Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallationEvent_Repository.Marshal(b, m, deterministic)
}
func (dst *InstallationEvent_Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallationEvent_Repository.Merge(dst, src)
}
func (m *InstallationEvent_Repository) XXX_Size() int {
	return xxx_messageInfo_InstallationEvent_Repository.Size(m)
}
func (m *InstallationEvent_Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallationEvent_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_InstallationEvent_Repository proto.InternalMessageInfo

func (m *InstallationEvent_Repository) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type CreateInstallationEventRequest struct {
	InstallationEvent    *InstallationEvent `protobuf:"bytes,1,opt,name=installation_event,json=installationEvent,proto3" json:"installation_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateInstallationEventRequest) Reset()         { *m = CreateInstallationEventRequest{} }
func (m *CreateInstallationEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateInstallationEventRequest) ProtoMessage()    {}
func (*CreateInstallationEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_installation_event_3d701448f387c4fc, []int{2}
}
func (m *CreateInstallationEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInstallationEventRequest.Unmarshal(m, b)
}
func (m *CreateInstallationEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInstallationEventRequest.Marshal(b, m, deterministic)
}
func (dst *CreateInstallationEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInstallationEventRequest.Merge(dst, src)
}
func (m *CreateInstallationEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateInstallationEventRequest.Size(m)
}
func (m *CreateInstallationEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInstallationEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInstallationEventRequest proto.InternalMessageInfo

func (m *CreateInstallationEventRequest) GetInstallationEvent() *InstallationEvent {
	if m != nil {
		return m.InstallationEvent
	}
	return nil
}

func init() {
	proto.RegisterType((*Installation)(nil), "izumin5210.ghrsync.github.Installation")
	proto.RegisterType((*InstallationEvent)(nil), "izumin5210.ghrsync.github.InstallationEvent")
	proto.RegisterType((*InstallationEvent_Repository)(nil), "izumin5210.ghrsync.github.InstallationEvent.Repository")
	proto.RegisterType((*CreateInstallationEventRequest)(nil), "izumin5210.ghrsync.github.CreateInstallationEventRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InstallationEventServiceClient is the client API for InstallationEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InstallationEventServiceClient interface {
	CreateInstallationEvent(ctx context.Context, in *CreateInstallationEventRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type installationEventServiceClient struct {
	cc *grpc.ClientConn
}

func NewInstallationEventServiceClient(cc *grpc.ClientConn) InstallationEventServiceClient {
	return &installationEventServiceClient{cc}
}

func (c *installationEventServiceClient) CreateInstallationEvent(ctx context.Context, in *CreateInstallationEventRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/izumin5210.ghrsync.github.InstallationEventService/CreateInstallationEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstallationEventServiceServer is the server API for InstallationEventService service.
type InstallationEventServiceServer interface {
	CreateInstallationEvent(context.Context, *CreateInstallationEventRequest) (*empty.Empty, error)
}

func RegisterInstallationEventServiceServer(s *grpc.Server, srv InstallationEventServiceServer) {
	s.RegisterService(&_InstallationEventService_serviceDesc, srv)
}

func _InstallationEventService_CreateInstallationEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstallationEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallationEventServiceServer).CreateInstallationEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/izumin5210.ghrsync.github.InstallationEventService/CreateInstallationEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallationEventServiceServer).CreateInstallationEvent(ctx, req.(*CreateInstallationEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InstallationEventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "izumin5210.ghrsync.github.InstallationEventService",
	HandlerType: (*InstallationEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstallationEvent",
			Handler:    _InstallationEventService_CreateInstallationEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "installation_event.proto",
}

func init() {
	proto.RegisterFile("installation_event.proto", fileDescriptor_installation_event_3d701448f387c4fc)
}

var fileDescriptor_installation_event_3d701448f387c4fc = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x49, 0x0a, 0xe5, 0x76, 0xda, 0x7b, 0xa1, 0xb3, 0xe8, 0x8d, 0xa9, 0x94, 0x92, 0x8d,
	0x15, 0x64, 0x62, 0xa3, 0x52, 0xd4, 0x9d, 0xd2, 0x85, 0x08, 0x2e, 0xe2, 0xce, 0x2e, 0xca, 0x24,
	0x9d, 0xa6, 0x03, 0xc9, 0x4c, 0x4c, 0x26, 0x85, 0x0a, 0x82, 0xf8, 0x0a, 0x3e, 0x83, 0x2f, 0xe2,
	0x2b, 0xf8, 0x0a, 0x3e, 0x88, 0x64, 0x92, 0xd2, 0xd4, 0xd8, 0xa2, 0xab, 0x70, 0xfe, 0x7d, 0xe7,
	0x77, 0x32, 0x1f, 0xd0, 0x28, 0x8b, 0x05, 0xf6, 0x7d, 0x2c, 0x28, 0x67, 0x63, 0x32, 0x27, 0x4c,
	0xa0, 0x30, 0xe2, 0x82, 0xc3, 0x1d, 0xfa, 0x90, 0x04, 0x94, 0x9d, 0x58, 0xfd, 0x43, 0xe4, 0xcd,
	0xa2, 0x78, 0xc1, 0x5c, 0xe4, 0x51, 0x31, 0x4b, 0x1c, 0x7d, 0xd7, 0xe3, 0xdc, 0xf3, 0x89, 0x89,
	0x43, 0x6a, 0x62, 0xc6, 0xb8, 0x90, 0xd3, 0x71, 0x36, 0xa8, 0xb7, 0xf3, 0xaa, 0x8c, 0x9c, 0x64,
	0x6a, 0x92, 0x20, 0x14, 0x8b, 0xac, 0x68, 0x74, 0x40, 0xe3, 0xaa, 0xb0, 0x11, 0xfe, 0x03, 0x2a,
	0x9d, 0x68, 0x4a, 0x57, 0xe9, 0xfd, 0xb5, 0x55, 0x3a, 0x31, 0x9e, 0x54, 0xd0, 0x2c, 0x36, 0x0c,
	0x53, 0x22, 0xd8, 0x02, 0x55, 0xec, 0xa6, 0xa1, 0xec, 0xac, 0xd9, 0x79, 0x04, 0xaf, 0x41, 0xa3,
	0xc8, 0xaf, 0xa9, 0x5d, 0xa5, 0x57, 0xb7, 0xf6, 0xd0, 0x46, 0x74, 0x54, 0xd4, 0xb6, 0xd7, 0x86,
	0xe1, 0x08, 0x34, 0x22, 0x12, 0xf2, 0x98, 0x0a, 0x1e, 0x51, 0x12, 0x6b, 0x95, 0x6e, 0xa5, 0x57,
	0xb7, 0x06, 0x3f, 0x14, 0x93, 0xa0, 0xc8, 0x5e, 0x0a, 0x2c, 0xec, 0x35, 0x31, 0x7d, 0x1f, 0x80,
	0x55, 0x0d, 0xb6, 0x41, 0x6d, 0x9a, 0xf8, 0xfe, 0x98, 0xe1, 0x80, 0xe4, 0x27, 0xfd, 0x49, 0x13,
	0x37, 0x38, 0x20, 0xc6, 0x23, 0xe8, 0x5c, 0x46, 0x04, 0x0b, 0x52, 0x92, 0xb7, 0xc9, 0x7d, 0x42,
	0x62, 0x01, 0x47, 0x00, 0x96, 0x9f, 0x4d, 0xea, 0xd4, 0xad, 0x83, 0xdf, 0xf0, 0xda, 0x4d, 0xfa,
	0x35, 0x65, 0xbd, 0x29, 0x40, 0x2b, 0x35, 0xde, 0x92, 0x68, 0x4e, 0x5d, 0x02, 0x5f, 0x15, 0xf0,
	0x7f, 0x03, 0x1c, 0x3c, 0xdd, 0xb2, 0x79, 0xfb, 0x41, 0x7a, 0x0b, 0x65, 0x9e, 0x41, 0x4b, 0xcf,
	0xa0, 0x61, 0xea, 0x19, 0x63, 0xf0, 0xfc, 0xfe, 0xf1, 0xa2, 0xf6, 0x8d, 0xb6, 0x99, 0xe9, 0x98,
	0xe5, 0xb3, 0xe3, 0xb3, 0x6f, 0xfe, 0xc5, 0xc5, 0xf1, 0x9d, 0x95, 0x6f, 0x76, 0x79, 0x60, 0xae,
	0xb8, 0xcc, 0x9c, 0x4b, 0x5a, 0x37, 0xeb, 0x38, 0xcf, 0x3e, 0xe3, 0xd0, 0x71, 0xaa, 0x72, 0xfd,
	0xd1, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0xa0, 0x8a, 0x6a, 0x15, 0x03, 0x00, 0x00,
}
