// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pull_request_event.proto

package github_pb // import "github.com/izumin5210/ghrsync/api/github"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PullRequestEvent struct {
	PullRequestEventId   string   `protobuf:"bytes,1,opt,name=pull_request_event_id,json=pullRequestEventId,proto3" json:"pull_request_event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequestEvent) Reset()         { *m = PullRequestEvent{} }
func (m *PullRequestEvent) String() string { return proto.CompactTextString(m) }
func (*PullRequestEvent) ProtoMessage()    {}
func (*PullRequestEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_pull_request_event_c14ba85667f62945, []int{0}
}
func (m *PullRequestEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequestEvent.Unmarshal(m, b)
}
func (m *PullRequestEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequestEvent.Marshal(b, m, deterministic)
}
func (dst *PullRequestEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequestEvent.Merge(dst, src)
}
func (m *PullRequestEvent) XXX_Size() int {
	return xxx_messageInfo_PullRequestEvent.Size(m)
}
func (m *PullRequestEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequestEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequestEvent proto.InternalMessageInfo

func (m *PullRequestEvent) GetPullRequestEventId() string {
	if m != nil {
		return m.PullRequestEventId
	}
	return ""
}

type CreatePullRequestEventRequest struct {
	PullRequestEvent     *PullRequestEvent `protobuf:"bytes,1,opt,name=pull_request_event,json=pullRequestEvent,proto3" json:"pull_request_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreatePullRequestEventRequest) Reset()         { *m = CreatePullRequestEventRequest{} }
func (m *CreatePullRequestEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePullRequestEventRequest) ProtoMessage()    {}
func (*CreatePullRequestEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pull_request_event_c14ba85667f62945, []int{1}
}
func (m *CreatePullRequestEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePullRequestEventRequest.Unmarshal(m, b)
}
func (m *CreatePullRequestEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePullRequestEventRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePullRequestEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePullRequestEventRequest.Merge(dst, src)
}
func (m *CreatePullRequestEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePullRequestEventRequest.Size(m)
}
func (m *CreatePullRequestEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePullRequestEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePullRequestEventRequest proto.InternalMessageInfo

func (m *CreatePullRequestEventRequest) GetPullRequestEvent() *PullRequestEvent {
	if m != nil {
		return m.PullRequestEvent
	}
	return nil
}

func init() {
	proto.RegisterType((*PullRequestEvent)(nil), "izumin5210.ghrsync.github.PullRequestEvent")
	proto.RegisterType((*CreatePullRequestEventRequest)(nil), "izumin5210.ghrsync.github.CreatePullRequestEventRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PullRequestEventServiceClient is the client API for PullRequestEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PullRequestEventServiceClient interface {
	CreatePullRequestEvent(ctx context.Context, in *CreatePullRequestEventRequest, opts ...grpc.CallOption) (*PullRequestEvent, error)
}

type pullRequestEventServiceClient struct {
	cc *grpc.ClientConn
}

func NewPullRequestEventServiceClient(cc *grpc.ClientConn) PullRequestEventServiceClient {
	return &pullRequestEventServiceClient{cc}
}

func (c *pullRequestEventServiceClient) CreatePullRequestEvent(ctx context.Context, in *CreatePullRequestEventRequest, opts ...grpc.CallOption) (*PullRequestEvent, error) {
	out := new(PullRequestEvent)
	err := c.cc.Invoke(ctx, "/izumin5210.ghrsync.github.PullRequestEventService/CreatePullRequestEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PullRequestEventServiceServer is the server API for PullRequestEventService service.
type PullRequestEventServiceServer interface {
	CreatePullRequestEvent(context.Context, *CreatePullRequestEventRequest) (*PullRequestEvent, error)
}

func RegisterPullRequestEventServiceServer(s *grpc.Server, srv PullRequestEventServiceServer) {
	s.RegisterService(&_PullRequestEventService_serviceDesc, srv)
}

func _PullRequestEventService_CreatePullRequestEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePullRequestEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PullRequestEventServiceServer).CreatePullRequestEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/izumin5210.ghrsync.github.PullRequestEventService/CreatePullRequestEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PullRequestEventServiceServer).CreatePullRequestEvent(ctx, req.(*CreatePullRequestEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PullRequestEventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "izumin5210.ghrsync.github.PullRequestEventService",
	HandlerType: (*PullRequestEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePullRequestEvent",
			Handler:    _PullRequestEventService_CreatePullRequestEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pull_request_event.proto",
}

func init() {
	proto.RegisterFile("pull_request_event.proto", fileDescriptor_pull_request_event_c14ba85667f62945)
}

var fileDescriptor_pull_request_event_c14ba85667f62945 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xcd, 0xc9,
	0x89, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x89, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xcc, 0xac, 0x2a, 0xcd, 0xcd, 0xcc, 0x33, 0x35, 0x32, 0x34,
	0xd0, 0x4b, 0xcf, 0x28, 0x2a, 0xae, 0xcc, 0x4b, 0xd6, 0x4b, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0x92,
	0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb,
	0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x68, 0x54, 0x72, 0xe5, 0x12, 0x08, 0x28, 0xcd,
	0xc9, 0x09, 0x82, 0x98, 0xe9, 0x0a, 0x32, 0x52, 0xc8, 0x90, 0x4b, 0x14, 0xd3, 0xa2, 0xf8, 0xcc,
	0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa1, 0x02, 0x34, 0x0d, 0x9e, 0x29, 0x4a, 0x55,
	0x5c, 0xb2, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0xe8, 0x86, 0x41, 0xd9, 0x42, 0x91, 0x5c, 0x42,
	0x98, 0x66, 0x82, 0x0d, 0xe4, 0x36, 0xd2, 0xd6, 0xc3, 0xe9, 0x7a, 0x3d, 0x0c, 0xf3, 0x04, 0xd0,
	0x6d, 0x37, 0x3a, 0xcb, 0xc8, 0x25, 0x8e, 0xae, 0x2c, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55,
	0x68, 0x23, 0x23, 0x97, 0x18, 0x76, 0x87, 0x09, 0x59, 0xe0, 0xb1, 0x15, 0xaf, 0x5f, 0xa4, 0x48,
	0x71, 0xaf, 0x92, 0x41, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0xb4, 0x94, 0x44, 0xf4, 0x31, 0xfd, 0x5f,
	0x6c, 0x85, 0x25, 0x50, 0x9c, 0x4c, 0xa2, 0x8c, 0xa0, 0x86, 0x25, 0xe7, 0xe7, 0xea, 0x23, 0xac,
	0xd2, 0x87, 0x5a, 0x05, 0x8e, 0x49, 0x88, 0x0a, 0x6b, 0x08, 0x15, 0x5f, 0x90, 0x94, 0xc4, 0x06,
	0x8e, 0x4f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x70, 0xf2, 0xc7, 0x24, 0x02, 0x00,
	0x00,
}
