// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pull_request_event.proto

package github_pb // import "github.com/izumin5210/ghrsync/api/github"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PullRequest struct {
	Number               uint32              `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Head                 *PullRequest_Branch `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Merged               bool                `protobuf:"varint,3,opt,name=merged,proto3" json:"merged,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pull_request_event_772709ff9bc6d0ea, []int{0}
}
func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (dst *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(dst, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *PullRequest) GetHead() *PullRequest_Branch {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *PullRequest) GetMerged() bool {
	if m != nil {
		return m.Merged
	}
	return false
}

type PullRequest_Branch struct {
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Sha                  string   `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest_Branch) Reset()         { *m = PullRequest_Branch{} }
func (m *PullRequest_Branch) String() string { return proto.CompactTextString(m) }
func (*PullRequest_Branch) ProtoMessage()    {}
func (*PullRequest_Branch) Descriptor() ([]byte, []int) {
	return fileDescriptor_pull_request_event_772709ff9bc6d0ea, []int{0, 0}
}
func (m *PullRequest_Branch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest_Branch.Unmarshal(m, b)
}
func (m *PullRequest_Branch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest_Branch.Marshal(b, m, deterministic)
}
func (dst *PullRequest_Branch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest_Branch.Merge(dst, src)
}
func (m *PullRequest_Branch) XXX_Size() int {
	return xxx_messageInfo_PullRequest_Branch.Size(m)
}
func (m *PullRequest_Branch) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest_Branch.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest_Branch proto.InternalMessageInfo

func (m *PullRequest_Branch) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *PullRequest_Branch) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type PullRequestEvent struct {
	Action               string                         `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	PullRequest          *PullRequest                   `protobuf:"bytes,2,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	Repository           *PullRequestEvent_Repository   `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Installation         *PullRequestEvent_Installation `protobuf:"bytes,4,opt,name=installation,proto3" json:"installation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *PullRequestEvent) Reset()         { *m = PullRequestEvent{} }
func (m *PullRequestEvent) String() string { return proto.CompactTextString(m) }
func (*PullRequestEvent) ProtoMessage()    {}
func (*PullRequestEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_pull_request_event_772709ff9bc6d0ea, []int{1}
}
func (m *PullRequestEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequestEvent.Unmarshal(m, b)
}
func (m *PullRequestEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequestEvent.Marshal(b, m, deterministic)
}
func (dst *PullRequestEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequestEvent.Merge(dst, src)
}
func (m *PullRequestEvent) XXX_Size() int {
	return xxx_messageInfo_PullRequestEvent.Size(m)
}
func (m *PullRequestEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequestEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequestEvent proto.InternalMessageInfo

func (m *PullRequestEvent) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *PullRequestEvent) GetPullRequest() *PullRequest {
	if m != nil {
		return m.PullRequest
	}
	return nil
}

func (m *PullRequestEvent) GetRepository() *PullRequestEvent_Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *PullRequestEvent) GetInstallation() *PullRequestEvent_Installation {
	if m != nil {
		return m.Installation
	}
	return nil
}

type PullRequestEvent_Repository struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequestEvent_Repository) Reset()         { *m = PullRequestEvent_Repository{} }
func (m *PullRequestEvent_Repository) String() string { return proto.CompactTextString(m) }
func (*PullRequestEvent_Repository) ProtoMessage()    {}
func (*PullRequestEvent_Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_pull_request_event_772709ff9bc6d0ea, []int{1, 0}
}
func (m *PullRequestEvent_Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequestEvent_Repository.Unmarshal(m, b)
}
func (m *PullRequestEvent_Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequestEvent_Repository.Marshal(b, m, deterministic)
}
func (dst *PullRequestEvent_Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequestEvent_Repository.Merge(dst, src)
}
func (m *PullRequestEvent_Repository) XXX_Size() int {
	return xxx_messageInfo_PullRequestEvent_Repository.Size(m)
}
func (m *PullRequestEvent_Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequestEvent_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequestEvent_Repository proto.InternalMessageInfo

func (m *PullRequestEvent_Repository) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type PullRequestEvent_Installation struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequestEvent_Installation) Reset()         { *m = PullRequestEvent_Installation{} }
func (m *PullRequestEvent_Installation) String() string { return proto.CompactTextString(m) }
func (*PullRequestEvent_Installation) ProtoMessage()    {}
func (*PullRequestEvent_Installation) Descriptor() ([]byte, []int) {
	return fileDescriptor_pull_request_event_772709ff9bc6d0ea, []int{1, 1}
}
func (m *PullRequestEvent_Installation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequestEvent_Installation.Unmarshal(m, b)
}
func (m *PullRequestEvent_Installation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequestEvent_Installation.Marshal(b, m, deterministic)
}
func (dst *PullRequestEvent_Installation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequestEvent_Installation.Merge(dst, src)
}
func (m *PullRequestEvent_Installation) XXX_Size() int {
	return xxx_messageInfo_PullRequestEvent_Installation.Size(m)
}
func (m *PullRequestEvent_Installation) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequestEvent_Installation.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequestEvent_Installation proto.InternalMessageInfo

func (m *PullRequestEvent_Installation) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreatePullRequestEventRequest struct {
	PullRequestEvent     *PullRequestEvent `protobuf:"bytes,1,opt,name=pull_request_event,json=pullRequestEvent,proto3" json:"pull_request_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreatePullRequestEventRequest) Reset()         { *m = CreatePullRequestEventRequest{} }
func (m *CreatePullRequestEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePullRequestEventRequest) ProtoMessage()    {}
func (*CreatePullRequestEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pull_request_event_772709ff9bc6d0ea, []int{2}
}
func (m *CreatePullRequestEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePullRequestEventRequest.Unmarshal(m, b)
}
func (m *CreatePullRequestEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePullRequestEventRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePullRequestEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePullRequestEventRequest.Merge(dst, src)
}
func (m *CreatePullRequestEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePullRequestEventRequest.Size(m)
}
func (m *CreatePullRequestEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePullRequestEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePullRequestEventRequest proto.InternalMessageInfo

func (m *CreatePullRequestEventRequest) GetPullRequestEvent() *PullRequestEvent {
	if m != nil {
		return m.PullRequestEvent
	}
	return nil
}

func init() {
	proto.RegisterType((*PullRequest)(nil), "izumin5210.ghrsync.github.PullRequest")
	proto.RegisterType((*PullRequest_Branch)(nil), "izumin5210.ghrsync.github.PullRequest.Branch")
	proto.RegisterType((*PullRequestEvent)(nil), "izumin5210.ghrsync.github.PullRequestEvent")
	proto.RegisterType((*PullRequestEvent_Repository)(nil), "izumin5210.ghrsync.github.PullRequestEvent.Repository")
	proto.RegisterType((*PullRequestEvent_Installation)(nil), "izumin5210.ghrsync.github.PullRequestEvent.Installation")
	proto.RegisterType((*CreatePullRequestEventRequest)(nil), "izumin5210.ghrsync.github.CreatePullRequestEventRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PullRequestEventServiceClient is the client API for PullRequestEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PullRequestEventServiceClient interface {
	CreatePullRequestEvent(ctx context.Context, in *CreatePullRequestEventRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type pullRequestEventServiceClient struct {
	cc *grpc.ClientConn
}

func NewPullRequestEventServiceClient(cc *grpc.ClientConn) PullRequestEventServiceClient {
	return &pullRequestEventServiceClient{cc}
}

func (c *pullRequestEventServiceClient) CreatePullRequestEvent(ctx context.Context, in *CreatePullRequestEventRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/izumin5210.ghrsync.github.PullRequestEventService/CreatePullRequestEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PullRequestEventServiceServer is the server API for PullRequestEventService service.
type PullRequestEventServiceServer interface {
	CreatePullRequestEvent(context.Context, *CreatePullRequestEventRequest) (*empty.Empty, error)
}

func RegisterPullRequestEventServiceServer(s *grpc.Server, srv PullRequestEventServiceServer) {
	s.RegisterService(&_PullRequestEventService_serviceDesc, srv)
}

func _PullRequestEventService_CreatePullRequestEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePullRequestEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PullRequestEventServiceServer).CreatePullRequestEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/izumin5210.ghrsync.github.PullRequestEventService/CreatePullRequestEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PullRequestEventServiceServer).CreatePullRequestEvent(ctx, req.(*CreatePullRequestEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PullRequestEventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "izumin5210.ghrsync.github.PullRequestEventService",
	HandlerType: (*PullRequestEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePullRequestEvent",
			Handler:    _PullRequestEventService_CreatePullRequestEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pull_request_event.proto",
}

func init() {
	proto.RegisterFile("pull_request_event.proto", fileDescriptor_pull_request_event_772709ff9bc6d0ea)
}

var fileDescriptor_pull_request_event_772709ff9bc6d0ea = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x56, 0xd2, 0x6a, 0xd5, 0x9d, 0x2c, 0x68, 0xe5, 0xc3, 0x12, 0xb2, 0x80, 0x56, 0x39, 0xa0,
	0x45, 0x80, 0x43, 0xc3, 0xaf, 0xe0, 0x44, 0x51, 0x0f, 0xbd, 0x20, 0x64, 0x24, 0x24, 0x10, 0xd2,
	0xca, 0xc9, 0x7a, 0x13, 0x4b, 0x89, 0x13, 0x1c, 0xa7, 0xd2, 0xf6, 0xc8, 0x2b, 0xf0, 0x08, 0xdc,
	0x79, 0x05, 0x1e, 0x82, 0x57, 0xe0, 0x19, 0x38, 0x23, 0x3b, 0x2e, 0x0d, 0xdb, 0x1f, 0xb5, 0xa7,
	0x78, 0xc6, 0x33, 0xdf, 0xf7, 0xcd, 0x17, 0x0f, 0xf8, 0x75, 0x5b, 0x14, 0x0b, 0xc9, 0xbe, 0xb4,
	0xac, 0x51, 0x0b, 0x76, 0xc8, 0x84, 0xc2, 0xb5, 0xac, 0x54, 0x85, 0x6e, 0xf2, 0xa3, 0xb6, 0xe4,
	0xe2, 0x69, 0xbc, 0xfb, 0x08, 0x67, 0xb9, 0x6c, 0xd6, 0x22, 0xc5, 0x19, 0x57, 0x79, 0x9b, 0x04,
	0xb7, 0xb2, 0xaa, 0xca, 0x0a, 0x16, 0xd1, 0x9a, 0x47, 0x54, 0x88, 0x4a, 0x51, 0xc5, 0x2b, 0xd1,
	0x74, 0x8d, 0xc1, 0xd4, 0xde, 0x9a, 0x28, 0x69, 0x57, 0x11, 0x2b, 0x6b, 0xb5, 0xee, 0x2e, 0xc3,
	0x1f, 0x0e, 0x78, 0xef, 0xda, 0xa2, 0x20, 0x1d, 0x23, 0x9a, 0xc0, 0x40, 0xb4, 0x65, 0xc2, 0xa4,
	0xef, 0xcc, 0x9c, 0xf9, 0x35, 0x62, 0x23, 0xf4, 0x1a, 0xb6, 0x73, 0x46, 0x97, 0xbe, 0x3b, 0x73,
	0xe6, 0x5e, 0xfc, 0x10, 0x9f, 0x2b, 0x06, 0xf7, 0xd0, 0xf0, 0x9e, 0xa4, 0x22, 0xcd, 0x89, 0x69,
	0xd5, 0xd0, 0x25, 0x93, 0x19, 0x5b, 0xfa, 0x5b, 0x33, 0x67, 0xbe, 0x43, 0x6c, 0x14, 0x3c, 0x80,
	0x41, 0x57, 0x87, 0xc6, 0xb0, 0x25, 0xd9, 0xca, 0x70, 0x0c, 0x89, 0x3e, 0xea, 0x4c, 0x93, 0x53,
	0xa3, 0x65, 0x48, 0xf4, 0x31, 0xfc, 0xe3, 0xc2, 0xb8, 0x47, 0xb1, 0xaf, 0x1d, 0xd2, 0xd0, 0x34,
	0xd5, 0x33, 0xdb, 0x4a, 0x1b, 0xa1, 0x03, 0x18, 0xf5, 0xfd, 0xb4, 0xea, 0xef, 0x5e, 0x4e, 0x3d,
	0xf1, 0xea, 0x9e, 0x31, 0x1f, 0x00, 0x24, 0xab, 0xab, 0x86, 0xab, 0x4a, 0xae, 0xcd, 0x04, 0x5e,
	0xfc, 0xec, 0x72, 0x40, 0x46, 0x23, 0x26, 0xff, 0xba, 0x49, 0x0f, 0x09, 0x7d, 0x86, 0x11, 0x17,
	0x8d, 0xa2, 0x45, 0x61, 0x7e, 0x9a, 0xbf, 0x6d, 0x90, 0x5f, 0x5c, 0x05, 0xf9, 0xa0, 0xd7, 0x4f,
	0xfe, 0x43, 0x0b, 0xee, 0x01, 0x9c, 0xf0, 0xa2, 0x29, 0x0c, 0x57, 0xda, 0x0e, 0x41, 0x4b, 0x66,
	0x9d, 0xda, 0xd1, 0x89, 0xb7, 0xb4, 0x64, 0xc1, 0x1d, 0x18, 0xf5, 0x81, 0xd0, 0x75, 0x70, 0xf9,
	0xd2, 0xbe, 0x02, 0x97, 0x2f, 0xc3, 0x23, 0xb8, 0xfd, 0x46, 0x32, 0xaa, 0xd8, 0x26, 0xff, 0xb1,
	0x43, 0x1f, 0x01, 0x9d, 0x7e, 0xbc, 0x06, 0xc0, 0x8b, 0xef, 0x5f, 0x61, 0x1e, 0x32, 0xae, 0x37,
	0x32, 0xf1, 0x4f, 0x07, 0x6e, 0x6c, 0x96, 0xbd, 0x67, 0xf2, 0x90, 0xa7, 0x0c, 0x7d, 0x77, 0x60,
	0x72, 0xb6, 0x30, 0x74, 0x91, 0x8b, 0x17, 0xce, 0x12, 0x4c, 0x70, 0xb7, 0x34, 0xf8, 0x78, 0x69,
	0xf0, 0xbe, 0x5e, 0x9a, 0xf0, 0xf9, 0xd7, 0x5f, 0xbf, 0xbf, 0xb9, 0xbb, 0xe1, 0x34, 0xea, 0x60,
	0xa2, 0xd3, 0x13, 0x37, 0x2f, 0xcf, 0xb0, 0x61, 0xef, 0xc9, 0xa7, 0xd8, 0x12, 0xa7, 0x55, 0x19,
	0x9d, 0xc8, 0x8a, 0xac, 0x2c, 0xb3, 0xbb, 0x5d, 0xc5, 0xab, 0xee, 0xb3, 0xa8, 0x93, 0x64, 0x60,
	0xe8, 0x1f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x63, 0x3a, 0x38, 0x0c, 0x16, 0x04, 0x00, 0x00,
}
